CREATE INDEX `idx_gameweekScore_userTeamId` ON `gameweekScores` (`userTeamId`);--> statement-breakpoint
CREATE INDEX `idx_gameweekScore_gameweekId` ON `gameweekScores` (`gameweekId`);--> statement-breakpoint
CREATE INDEX `idx_gameweekScore_userTeamId_gameweekId` ON `gameweekScores` (`userTeamId`,`gameweekId`);--> statement-breakpoint
CREATE INDEX `idx_gameweek_leagueId` ON `gameweeks` (`leagueId`);--> statement-breakpoint
CREATE INDEX `idx_gameweek_status` ON `gameweeks` (`status`);--> statement-breakpoint
CREATE INDEX `idx_gameweek_leagueId_gameweekNumber` ON `gameweeks` (`leagueId`,`gameweekNumber`);--> statement-breakpoint
CREATE INDEX `idx_league_creatorId` ON `leagues` (`creatorId`);--> statement-breakpoint
CREATE INDEX `idx_league_status` ON `leagues` (`status`);--> statement-breakpoint
CREATE INDEX `idx_league_leagueType` ON `leagues` (`leagueType`);--> statement-breakpoint
CREATE INDEX `idx_match_homeTeamId` ON `matches` (`homeTeamId`);--> statement-breakpoint
CREATE INDEX `idx_match_awayTeamId` ON `matches` (`awayTeamId`);--> statement-breakpoint
CREATE INDEX `idx_match_status` ON `matches` (`status`);--> statement-breakpoint
CREATE INDEX `idx_match_matchDate` ON `matches` (`matchDate`);--> statement-breakpoint
CREATE INDEX `idx_playerGameweekStats_playerId` ON `playerGameweekStats` (`playerId`);--> statement-breakpoint
CREATE INDEX `idx_playerGameweekStats_gameweekId` ON `playerGameweekStats` (`gameweekId`);--> statement-breakpoint
CREATE INDEX `idx_playerGameweekStats_playerId_gameweekId` ON `playerGameweekStats` (`playerId`,`gameweekId`);--> statement-breakpoint
CREATE INDEX `idx_playerGameweekStats_totalPoints` ON `playerGameweekStats` (`totalPoints`);--> statement-breakpoint
CREATE INDEX `idx_playerPerformance_matchId` ON `playerPerformances` (`matchId`);--> statement-breakpoint
CREATE INDEX `idx_playerPerformance_playerId` ON `playerPerformances` (`playerId`);--> statement-breakpoint
CREATE INDEX `idx_playerPerformance_matchId_playerId` ON `playerPerformances` (`matchId`,`playerId`);--> statement-breakpoint
CREATE INDEX `idx_player_teamId` ON `players` (`teamId`);--> statement-breakpoint
CREATE INDEX `idx_player_position` ON `players` (`position`);--> statement-breakpoint
CREATE INDEX `idx_player_totalPoints` ON `players` (`totalPoints`);--> statement-breakpoint
CREATE INDEX `idx_transaction_userTeamId` ON `transactions` (`userTeamId`);--> statement-breakpoint
CREATE INDEX `idx_transaction_playerId` ON `transactions` (`playerId`);--> statement-breakpoint
CREATE INDEX `idx_transaction_transactionType` ON `transactions` (`transactionType`);--> statement-breakpoint
CREATE INDEX `idx_transaction_createdAt` ON `transactions` (`createdAt`);--> statement-breakpoint
CREATE INDEX `idx_userTeamPlayer_userTeamId` ON `userTeamPlayers` (`userTeamId`);--> statement-breakpoint
CREATE INDEX `idx_userTeamPlayer_playerId` ON `userTeamPlayers` (`playerId`);--> statement-breakpoint
CREATE INDEX `idx_userTeamPlayer_isCaptain` ON `userTeamPlayers` (`isCaptain`);--> statement-breakpoint
CREATE INDEX `idx_userTeam_userId` ON `userTeams` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_userTeam_leagueId` ON `userTeams` (`leagueId`);--> statement-breakpoint
CREATE INDEX `idx_userTeam_userId_leagueId` ON `userTeams` (`userId`,`leagueId`);--> statement-breakpoint
CREATE INDEX `idx_userTeam_totalPoints` ON `userTeams` (`totalPoints`);--> statement-breakpoint
CREATE INDEX `idx_user_email` ON `users` (`email`);--> statement-breakpoint
CREATE INDEX `idx_user_role` ON `users` (`role`);--> statement-breakpoint
CREATE INDEX `idx_user_createdAt` ON `users` (`createdAt`);